version: "3.4"

services:
  web:
    build:
      context: .
      target: pydev
    image: "${IMAGE}:pydev"
    ports:
      - "5000:5000"
    command: flask run -h 0.0.0.0
    volumes:
      - ./:/usr/src/app
    env_file: .env

  front_end:
    build:
      context: .
      target: jsdev
    image: "${IMAGE}:jsdev"
    ports:
      - "5001:5001"
    command: npm run watch -- --hmr-port 5001
    volumes:
      - "./${FLASK_APP}/static:/usr/src/app/${FLASK_APP}/static"
    env_file: .env
